version: "3.9"
services:
  db:
    image: "postgres:alpine"
    hostname: postgres
    environment:
      - POSTGRES_USER=nosiee
      - POSTGRES_PASSWORD=nosiee
      - POSTGRES_DB=hara
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
  hara:
    build: .
    environment:
      - API_ENDPOINT=:8080
      - HS512_KEY="NdRgUkXp2s5v8y/B?E(H+MbQeShVmYq3t6w9z$C&F)J@NcRfUjWnZr4u7x!A%D*G"

      - DATABASE_URL=postgres://nosiee:nosiee@postgres:5432/hara?sslmode=disable
      - DATABASE_DRIVER=postgres

      - UPLOAD_IMAGE_PATH=${UPLOAD_PATH}/images
      - UPLOAD_VIDEO_PATH=${UPLOAD_PATH}/videos

      - OUTPUT_IMAGE_PATH=${OUTPUT_PATH}/images
      - OUTPUT_VIDEO_PATH=${OUTPUT_PATH}/videos

      - GIN_MODE=release
    command: bash -c "bin/migrations --mtype up --mpath migrations/ && bin/hara"
    ports: 
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - haradata:${OUTPUT_PATH}

volumes:
  dbdata:
  haradata:
