CREATE TABLE IF NOT EXISTS users(
    ID SERIAL PRIMARY KEY,
    uuid VARCHAR (64) UNIQUE NOT NULL,
    username VARCHAR (20) UNIQUE NOT NULL,
    hash VARCHAR (120) NOT NULL,
    email VARCHAR (32) UNIQUE NOT NULL
);
